[build]
  publish = "public/"
  command = "gatsby build"

[context.production]
  command = "gatsby build"

[context.production.environment]
  CONTENTFUL_URL = 'cdn.contentful.com'

[context.branch-deploy]
  command = "gatsby build"

[context.dev]
  command = "gatsby build"
[context.dev.environment]
  CONTENTFUL_URL = 'cdn.contentful.com'

[context.preview]
  command = "gatsby build"
[context.preview.environment]
  CONTENTFUL_URL = 'preview.contentful.com'

[context.staging]
  command = "gatsby build"
[context.staging.environment] # 'staging' is a branch name
  CONTENTFUL_URL = 'cdn.contentful.com'

