[build]
  publish = "public/"
  command = "gatsby build"

# TODO it works but really?
[context.production]
  command = "gatsby build"
[context.production.environment]
  CONTENTFUL_URL = 'cdn.contentful.com'

[context.branch-deploy]
  command = "gatsby build"

[context.dev]
  command = "gatsby build"
[context.dev.environment]
  CONTENTFUL_URL = 'cdn.contentful.com'

[context.staging]
  command = "gatsby build"
[context.staging.environment] # 'staging' is a branch name
  CONTENTFUL_URL = 'cdn.contentful.com'

